pipeline:
  name: Display full branch name
  identifier: Display_full_branch_name
  tags: {}
  projectIdentifier: Pankaj
  orgIdentifier: default
  stages:
    - stage:
        name: S1
        identifier: S1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo S1
                          exit 0
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
