pipeline:
  name: Display full branch name
  identifier: Display_full_branch_name
  tags: {}
  projectIdentifier: Pankaj
  orgIdentifier: default
  stages:
    - stage:
        name: S1
        identifier: S1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: S1
                  identifier: S1
                  template:
                    templateRef: Display_full_branch_name
                    versionLabel: V1
                    templateInputs:
                      type: ShellScript
                      timeout: <+input>
        tags: {}
